### ISSUE TITLE
[BUG] IP Limit Valid Time not working

### ISSUE THREAD

**Issue by bobhenl** [Elytrium/LimboAuth#186]
**Describe the bug**
Hello, there's issue with IP Limit Valid Time, because it's not working. 
```yml
  ip-limit-registrations: 3
  totp-recovery-codes-amount: 16
  # Time in milliseconds, when ip limit works, set to 0 for disable.
  ip-limit-valid-time: 1296000000
```
![image](https://github.com/user-attachments/assets/989e166a-899c-4cb5-ab00-bccc72615695)
all are registered since 3/12/2024 (less than a week)

First one is from 3/12 and the other three are from 7/12

Even when it should be limited for 15d for 3 accounts only (1296000000ms = 15d) 

**To Reproduce**
1. Set 'ip-limit-registrations' in config to '2' and `ip-limit-valid-time` to `1296000000`.
2. Try to make more than 2 accounts within 15d, just instantly make 3 accounts or more.
3. You see you can make them.

**Expected behavior**
It shouldn't let you make new accounts.

**Screenshots**
![image](https://github.com/user-attachments/assets/de073448-44fc-454d-a970-c8e19aab3738)
in less than 15d 4 accounts while only 3 are allowed

**Server Info (please complete the following information):**
 - All Limbo plugins versions:
 - LimboAuth https://modrinth.com/plugin/limboauth/version/39e6653 (tested on this & even newer builds)
 - LimboAPI https://modrinth.com/plugin/limboapi/version/be15850
 - LimboFilter https://modrinth.com/plugin/limbofilter/version/21250c4
